.\Manpage pour json2txt.
.\Contact zoeurk.gmail.com
.TH man 1 "25 septembre 2024" "0.1" "json2txt man page"
.SH NAME
json2txt \- convertir des fichiers json
.SH SYNOPSIS
json2txt OPTIONS
.SH DESCRIPTION
Outil convertir des fichiers json
.SH OPTIONS
.TP
.BR \-J , " \-\-json
Inhibit the output of json.
.TP
.BR \-T , " \-\-text
Inhibit the output of text.
.TP
.BR \-s , " \-\-sort "\fIasc|dsc|none\fR
sort json and text;
.TP
.BR \-t , " \-\-test
No test
.TP
.BR \-w , " \-\-warning "\fItrue|false|none\fR
On warning
.EX
true		exit on warning
false	just emit warning
none		do nothing
.EE
.TP
.BR
.SH BUGS
Doesn't check for limits
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
