.\Manpage pour json2txt header.
.\Contact zoeurk.gmail.com
.TH man 3 "25 septembre 2024" "0.1" "json2txt header man page"
.SH NAME
json2txt.h
.SH SYNOPSIS
json2txt library documentation
.SH DESCRIPTION
.TP
.EX
#define INIT_JSON(BUFSIZE, ALLOC_SIZE, CHARS, buffer) { 0, BUFSIZE, ALLOC_SIZE, CHARS, buffer, NULL, 0, 0, 1, NULL, NULL, 0 }
.EE
.TP
.EX
enum TYPE{
	ARRAY = 1,
	PAIR = 2,
	SET = 4
};
.EE
.TP
.EX
enum VAL{
	INT = 0,
	STRING = 1,
	VOID = 2
};
.EE
.TP
.EX
enum KIND{
	NEW,
	SUB,
	NEXT
};
.EE
.TP
struct json_parser
.EX
\fBstruct json_parser\fR{
	\fBint\fR file;				/*file descriptor(FD) to analyse*/
	\fBunsigned\fR int buflen;	/*len of the buffer used for read the FD*/
	\fBsize\fR_t stock_buf;		/*stock buffer size to increment*/
	\fBchar\fR *chars;			/*chars to exclude (eg:" \\t\\n")*/
	\fBchar\fR *buffer;			/*buffer used tor read the FD*/
	\fBchar\fR *buf;			/*pointer used for read buffer*/
	\fBsize\fR_t len;			/*len of stock*/
	\fBssize\fR_t r_len;			/*len read by read_fn*/
	\fBssize\fR_t offset;		/*position in the FD*/
	\fBchar\fR *pstock;			/*pointer to stock for write in stock*/
	\fBchar\fR *stock;			/*the stockage buffer*/
	\fBsize\fR_t stock_size;		/*size of stock*/
};
.EE
.BR
.TP
struct json
.EX
\fBstruct json\fR{
	\fBenum TYPE\fR type;			/*Type of data*/
	\fBenum VAL\fR t_val;			/*Type of Value of the data*/
	struct{
		union{
			\fBsize_t\fR index;		/*index in array*/
			\fBchar\fR *key;		/*key name of this entry*/
		}name;
		\fBchar\fR *value;			/*value of this entry if she is set*/
	}value;
	\fBstruct\fR json *next;
	\fBstruct\fR json *prev;
	\fBstruct\fR json *sub;
	\fBstruct\fR json *up;
};
.EE
.BR
.TP
\fBssize_t\fR read_fn(\fBstruct json_parser\fR *p);
Read the json FD;
.BR
.TP
\fBvoid\fR readchar(\fBssize_t\fR *offset, \fBchar\fR **str, const \fBchar\fR *not);
Read the json buffer and squize chars, update the offset
.BR
.TP
\fBvoid\fR allocstr(\fBchar\fR **buffer, \fBsize_t\fR lentoadd);
Alloc/realloc buffer with lentoadd
.BR
.TP
\fBvoid\fR *json_create(\fBstruct json\fR **j, \fBenum KIND\fR kind, \fBenum TYPE\fR type);
Create a json structure by kind, and set type. *j is set to the new position and return the entering *json.
.BR
.TP
\fBvoid\fR *getint(\fBstruct json_parser\fR *p);
Read an integer(/boolean) from the json buffer and return it.
.BR
.TP
\fBvoid\fR *getstr(\fBstruct json_parser\fR *p);
Read an string from the json buffer and return it.
.BR
.TP
\fBvoid\fR *array(\fBstruct json_parser\fR *p, \fBstruct json\fR **j);
Read an array detected in json buffer.
.BR
.TP
\fBvoid\fR *pair(\fBstruct json_parser\fR *p, \fBstruct json\fR **j);
Read an pair(keys) detected in json buffer.
.BR
.TP
\fBssize_t\fR json_sort(\fBstruct json\fR *j, \fBchar\fR ***order, \fBint\fR sort, \fBint\fR warn_only);
Sort the current *j, and sort it in an array 'order'. Return the number elements in the array.
.EX
sort is how:
1	=> ascendant.
-1	=> descendent
0	=> none (is used for check duplicate keys)
.EE
.EX
warn_only:
1	=> just emit warning.
0	=> return -1 on duplicate entry
-1	=> no warning, never return -1
.EE
.BR
.TP
\fBint\fR duplicate_keys(\fBstruct json\fR *j, \fBint\fR warning_only);
Search for duplicate keys and bad numbers. Use json_sort().
.BR
.TP
\fBvoid\fR json_print(\fBstruct json\fR *j, \fBint\fR sort, \fBsize_t\fR space, \fBchar\fR c_sp, \fBsize_t\fR count, \fBint\fR warn_only);
Print FD in json format. Use json_sort().
.EX
\fIspace\fR is the number of \fIc_sp\fR used for space.
if \fIc_sp\fR == 0 no space are appliqued
.EE
.BR
.TP
\fBvoid\fR json2txt(\fBstruct json\fR *j, \fBint\fR sort, \fBchar\fR *string, \fBint\fR warn_only);
Print FD in the form text. Use json_sort().
.BR
.TP
\fBvoid\fR json_reset_flags(\fBstruct json\fR *j);
Reset type (with SET) in all the json structure.
.BR
.TP
\fBvoid\fR json_destroy(\fBstruct json\fR **j);
Destroy the json structure
.BR
.SH BUGS
.EX
Doesn't check limits
	NO WARANTY WARNING
.EE
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
