Document: json2txt
Title: Debian json2txt Manual
Author: <insert document author here>
Abstract: This manual describes what json2txt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/json2txt/json2txt.sgml.gz

Format: postscript
Files: /usr/share/doc/json2txt/json2txt.ps.gz

Format: text
Files: /usr/share/doc/json2txt/json2txt.text.gz

Format: HTML
Index: /usr/share/doc/json2txt/html/index.html
Files: /usr/share/doc/json2txt/html/*.html
