.\Manpage pour json2txt.
.\Contact zoeurk.gmail.com
.TH man 1 "9 Aout 2025" "0.3" "json2txt man page"
.SH NAME
json2txt \- convertir un flux json
.SH SYNOPSIS
json2txt OPTIONS
.SH DESCRIPTION
Outil pour convertir un flux json
.SH OPTIONS
.TP
.BR \-J , " \-\-json"
Inhibit the output of json.
.TP
.BR \-T , " \-\-text"
Inhibit the output of text.
.TP
.BR \-s , " \-\-sort "\fIasc|dsc|none\fR
sort json and text;
.TP
.BR \-t , " \-\-test"
No test
.TP
.BR \-w , " \-\-warning "\fItrue|false|none\fR
On warning
.EX
true		exit on warning
false	just emit warning
none		do nothing
.EE
.TP
.BR \-e , " \-\-empty"
Print empty array in the text format
.TP
.BR \-r , "\-\-rfc"
Try to be rfc compliant
.TP
.BR Exit\ Code:
.EX
0	=> Success
< 134	=> libc errors
255 -1	=> Before, After JSON data.
255 -2	=> Array error
255 -3	=> Object error
255 -4	=> Expected end of string
255 -5	=> Invalid number
255 -6	=> Invalid boolean
255 -7	=> Malformed JSON data
.EE
.TP
.SH BUGS
Doesn't check for limits
A voir...(surtout --rfc)
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
