GCC=gcc
AR=ar
OPTIONS_LIB=-U STRICT_NUM -D EXPLICIT_SIGN 
ERROR=-Werror
OPT=-Wall -Wpadded -Wextra
OPTIONS=$(OPT) -ansi -pedantic -g $(OPTIONS_LIB)
FILE=json2txt
OUTFILE=json2txt
MAIN=./main
all: all-shared all-static

all-shared: object shared
	$(GCC) $(MAIN)/main.o -o $(OUTFILE) $(OPTIONS) -L./lib -l$(OUTFILE)

all-static: object static
	$(GCC) -static $(MAIN)/main.o -o $(OUTFILE)-static $(OPTIONS) -L./lib -l$(OUTFILE)

object:
	$(GCC) -c $(MAIN)/main.c -o $(MAIN)/main.o $(OPTIONS)

static: static-lib
	$(AR) rcs ./lib/lib$(OUTFILE).a ./lib/$(OUTFILE)_static.o

shared: shared-lib
	$(GCC) -shared ./lib/$(OUTFILE)_shared.o -o ./lib/lib$(OUTFILE).so $(OPTIONS)

static-lib:
	$(GCC) -c ./lib/$(FILE).c -o ./lib/$(OUTFILE)_static.o $(OPTIONS)

shared-lib:
	$(GCC) -c -fPIC ./lib/$(FILE).c -o ./lib/$(OUTFILE)_shared.o $(OPTIONS)

clean:
	[ -e $(OUTFILE)-static ] && rm $(OUTFILE)-static
	[ -e lib/lib$(OUTFILE).so ] && rm lib/lib$(OUTFILE).so
	[ -e lib/lib$(OUTFILE).a ] && rm lib/lib$(OUTFILE).a
	[ -e $(OUTFILE) ] && rm $(OUTFILE)
	rm lib/*.o main/*.o

