.\Manpage pour json2txt.
.\Contact zoeurk.gmail.com
.TH man 1 "22 avril 2021" "1.0" "json2txt man page"
.SH NAME
json2txt \- "decompression" de fichiers json
.SH SYNOPSIS
json2txt [options] [fichier.json]
.SH DESCRIPTION
Outil qui permet de ressistiuer un fichier json dans un format brut.
.SH OPTIONS
.TP
.BR \-J
Ne pas afficher le format json.
.TP
.BR \-T
Ne pas afficher le format TXT.
.TP
.BR
.SH BUGS
Je sais pas
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
.SH SEE ALSO
